export const ADD_ENTIDADES_AUTO_MARCA = "ADD_ENTIDADES_AUTO_MARCA"
export const ADD_ENTIDADES_AUTO_MODELO = "ADD_ENTIDADES_AUTO_MODELO"
export const ADD_ENTIDADES_AUTO_PRECIO = "ADD_ENTIDADES_AUTO_PRECIO"