export const ADD_ENTIDADES_CASA_DOMICILIO = "ADD_ENTIDADES_CASA_DOMICILIO"
export const ADD_ENTIDADES_CASA_VALOR = "ADD_ENTIDADES_CASA_VALOR"
export const ADD_ENTIDADES_CASA_CP = "ADD_ENTIDADES_CASA_CP"