name: remote ssh command
on:
  push:
    tags:
      - 1.*

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and push Docker image
        uses: docker/setup-qemu-action@v1

      - run: docker login -u ${{secrets.DOCKER_USER}} --password ${{secrets.DOCKER_PASSWORD}}

      - run: docker build . -t creditas --build-arg NODE_ENV=production
      - run: docker tag creditas rubeng12/creditas-front:${GITHUB_REF##*/}
      - run: docker push rubeng12/creditas-front:${GITHUB_REF##*/}

